"""listing_tag_assoc many to many table created

Revision ID: c6d6defde195
Revises: dfcf20622785
Create Date: 2019-11-25 20:07:46.661788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d6defde195'
down_revision = 'dfcf20622785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_tag_assoc',
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['listing_tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_tag_assoc')
    # ### end Alembic commands ###
